################################################################################
#
# Register Walrus
#

- name: Debug walrus IP
  debug: msg="{{  hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.walrus }}"
  tags:
  - registration
  - debug

- name: Register Walrus
  shell: euca_conf --register-walrus --partition walrus
         --component "walrus-0001"
         --host "{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.walrus }}"
  ignore_errors: true
  tags:
  - registration

################################################################################
#
# Register UFS
#

- name: Register UFS
  shell: euca_conf --register-service -T user-api
         -N "ufs-0001"
         -H "{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.ufs }}"
  ignore_errors: true
  tags:
  - registration

################################################################################
#
# SC registration
#

- name: Register SC
  shell: euca_conf --register-sc
         --partition "{{ partition }}"
         --component "sc-0001"
         --host "{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.sc }}"
  ignore_errors: true
  tags:
  - registration

################################################################################
#
# CC registration
#

- name: Register CCs
  shell: euca_conf --register-cluster
         --partition "{{ partition }}"
         --component "cc-0001"
         --host "{{ hostvars[item]['ansible_' + cc_iface]['ipv4']['address'] }}"
  with_items: "{{ groups.cc }}"
  ignore_errors: true
  tags:
  - registration
