################################################################
#
# Gets ready for registration
#

- name: Check if Eucalyptus has been initialized
  stat: path={{ euca_db_path }}
  register: db_stat
  tags:
  - initialization
  - init_clc
  - clc

- name: Initialize Eucalyptus CLC
  shell: euca_conf --initialize
  when: db_stat.stat.exists == False
  tags:
  - registration
  - clc
  - init_clc
