################################################################
#
# Gets ready for registration
#

- name: Waiting for CLC to be listening
  wait_for: path=/var/log/eucalyptus/cloud-output.log search_regex="Detected Interfaces"
  tags:
  - registration

