---
# NCs Registration

- name: Start CC service
  service: name=eucalyptus-cc state=started

- name: Debug items
  debug: msg="{{ item  }}"
  with_items:
  - "{{ groups.nc }}"
  tags:
  - debug
  - nc_registration

- name: Register all NCs
  shell: euca_conf --register-nodes "{{ hostvars[item][hostvars[item]['nc_iface']]['ipv4']['address'] }}"
  with_items: "{{ groups.nc }}"
  when:
  - partition == "{{ hostvars[item]['partition'] }}"
  tags:
  - nc_registration

