---
#
# Register Walrus
#

- name: Register Walrus
  shell: euca_conf --register-walrus --partition walrus --host "{{ hostvars[item]['ansible_' + java_iface]['ipv4']['address'] }}" --component "{{ hostvars[item]['walrus_name'] }}"
  with_items: "{{ groups.walrus }}"
  ignore_errors: true
  tags:
  - registration
  when:
  - not use_vlans
